<a href="https://colab.research.google.com/github/Tanjib-Rafi/Social-Network-Ads/blob/main/knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import numpy as np
import pandas as pd
import sklearn

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/dataset KNN/Social_Network_Ads.csv')
X = dataset.iloc[:, [1,2,3]].values
y = dataset.iloc[:, -1].values

In [ ]:
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,0] = le.fit_transform(X[:,0])

In [ ]:
X

array([[1, 19, 19000],
       [1, 35, 20000],
       [0, 26, 43000],
       ...,
       [0, 50, 20000],
       [1, 36, 33000],
       [0, 49, 36000]], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [ ]:
X_train

array([[1, 58, 144000],
       [0, 59, 83000],
       [0, 24, 55000],
       [0, 26, 35000],
       [0, 58, 38000],
       [0, 42, 80000],
       [0, 40, 75000],
       [1, 59, 130000],
       [0, 46, 41000],
       [0, 41, 60000],
       [1, 42, 64000],
       [0, 37, 146000],
       [0, 23, 48000],
       [1, 25, 33000],
       [1, 24, 84000],
       [0, 27, 96000],
       [1, 23, 63000],
       [1, 48, 33000],
       [1, 48, 90000],
       [1, 42, 104000],
       [0, 44, 39000],
       [1, 32, 120000],
       [0, 38, 50000],
       [0, 32, 135000],
       [0, 52, 21000],
       [0, 53, 104000],
       [1, 39, 42000],
       [1, 38, 61000],
       [0, 36, 50000],
       [0, 36, 63000],
       [0, 35, 25000],
       [1, 35, 50000],
       [1, 42, 73000],
       [0, 47, 49000],
       [0, 59, 29000],
       [1, 49, 65000],
       [0, 45, 131000],
       [0, 31, 89000],
       [0, 46, 82000],
       [0, 47, 51000],
       [1, 26, 15000],
       [1, 60, 102000],
       [0, 38, 112000],
 

In [ ]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler
sc = MinMaxScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
X_train

array([[1.        , 0.95238095, 0.95555556],
       [0.        , 0.97619048, 0.5037037 ],
       [0.        , 0.14285714, 0.2962963 ],
       [0.        , 0.19047619, 0.14814815],
       [0.        , 0.95238095, 0.17037037],
       [0.        , 0.57142857, 0.48148148],
       [0.        , 0.52380952, 0.44444444],
       [1.        , 0.97619048, 0.85185185],
       [0.        , 0.66666667, 0.19259259],
       [0.        , 0.54761905, 0.33333333],
       [1.        , 0.57142857, 0.36296296],
       [0.        , 0.45238095, 0.97037037],
       [0.        , 0.11904762, 0.24444444],
       [1.        , 0.16666667, 0.13333333],
       [1.        , 0.14285714, 0.51111111],
       [0.        , 0.21428571, 0.6       ],
       [1.        , 0.11904762, 0.35555556],
       [1.        , 0.71428571, 0.13333333],
       [1.        , 0.71428571, 0.55555556],
       [1.        , 0.57142857, 0.65925926],
       [0.        , 0.61904762, 0.17777778],
       [1.        , 0.33333333, 0.77777778],
       [0.

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'euclidean')
classifier.fit(X_train, y_train)


KNeighborsClassifier(metric='euclidean')

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1])

In [ ]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1])

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test,y_pred)

In [ ]:
print(cm)

[[55  3]
 [ 1 21]]


In [ ]:
print(ac)

0.95
